### ISSUE TITLE
Change sender name for verification_start() and verification_check()

### ISSUE THREAD

**Issue by rotimi-best** [evilpacket/node-authy#30]
### How do I change AUTHMSG and Verify to MyAppName?

![image](https://user-images.githubusercontent.com/31730715/60173709-0ad6d800-9818-11e9-94eb-c034ac6dd0f9.png)
![image](https://user-images.githubusercontent.com/31730715/60173761-26da7980-9818-11e9-8d91-8446794f0ad9.png)

**Comment by josh-authy** [comment]
AUTHMSG is an alpha sender ID registered to send messages in that country.  You can't change it if you're using Verify.  If you want to register your own sender ids and create your own number pools, you can certainly do that on the Twilio platform.   Verify is a turnkey solution intended to remove all of that dev and maintenance effort.

Here is an article about Alpha Sender IDs.
https://support.twilio.com/hc/en-us/articles/223133767-International-support-for-Alphanumeric-Sender-ID
